# Generated by Django 4.1 on 2022-09-05 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TopsListGenerator", "0005_group"),
    ]

    operations = [
        migrations.DeleteModel(name="Group",),
    ]
