# Generated by Django 4.1 on 2022-10-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TopsListGenerator", "0007_playlist_songs"),
    ]

    operations = [
        migrations.AddField(
            model_name="topsgroup",
            name="max_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="topsgroup",
            name="min_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="topsgroup",
            name="playlistlength",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
